### ISSUE TITLE
Add an X (clear) button to the search bar 

### ISSUE THREAD

**Issue by kleinerPanzer** [Duosmium/duosmium-ruby#8]
Not a huge issue, I just think it'd be nice to not have to do Ctrl+A Backspace/hold Backspace to delete what you've entered into the search bar

real-world examples
![image](https://user-images.githubusercontent.com/70746595/107739494-97c0f480-6cce-11eb-9b65-ea052e69a8c0.png)

perhaps looks like this
![image](https://user-images.githubusercontent.com/70746595/107739445-85df5180-6cce-11eb-98c1-5e3130200977.png)

**Comment by smayya337** [comment]
Good idea, I'll look into adding that.

**Comment by smayya337** [comment]
OK, the clear function is available on Safari and Chromium-based browsers, but not on Firefox... I'll see what I can do about it tomorrow morning (probably will need to write up some JS).
